{
 "title": "M5StickC Plus2 - Celsius",
 "description": "Example Dashboard to visualise your temperature/humidity/pressure metrics when pairing the M5StickC Plus2 with the ENV III sensor. ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "External Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_temp{}", "legendFormat": " " }
   ]
  },
  {
   "title": "External Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "m5stick_temp{}", "legendFormat": "{{__name__}} - {{location}}" }
   ]
  },
  {
   "title": "Battery Volt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_bat_volt{} / 1000", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_pressure{} / 100", "legendFormat": " " }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "m5stick_pressure{} / 100",
     "legendFormat": "m5stick_pressure - {{location}}"
    }
   ]
  },
  {
   "title": "Battery Recharging Current",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_bat_current{}", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_hum{}", "legendFormat": " " }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    { "expr": "m5stick_hum{}", "legendFormat": "{{__name__}} - {{location}}" }
   ]
  },
  {
   "title": "Battery Charge Left",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "m5stick_bat_level{}", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}